baseURL = "https://blog.kittycash.io/"
languageCode = "en-us"
title = "Kitty Cash Blog"
defaultContentLanguage = "en"

#googleAnalytics = ""
#disqusShortname = ""

# hugo-xmin specific variables
theme = "kittycash"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

# enables ```lang ``` style syntax highlighted blocks
pygmentsCodeFences = true
pygmentsStyle = "murphy"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    identifier = "categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    identifier = "tags"
    url = "/tags/"
    weight = 3

[[menu.footer]]
  name = "kittycash.io"
  url = "https://www.kittycash.io/"
  weight = 1

[[menu.footer]]
  name = "Github"
  url = "https://github.com/kittycash"
  weight = 2

[author]
  name = "Kitty Cash"

[params]
  keywords = "kittycash"
  rss = "/index.xml"
  telegram = "https://t.me/kittycash"
  description = "Kitty Cash Project Updates"
  email = ""
  github = "kittycash"

[Languages]
[Languages.en]
  weight = -1
  title = "Kitty Cash Blog"
  languageName = "English"

[Languages.es]
    weight = 4
    title = "Kitty Cash Blog"
    languageName = "Español"

[Languages.de]
    weight = 5
    title = "Kitty Cash Blog"
    languageName = "Deutsch"

[Languages.fr]
    weight = 8
    title = "Kitty Cash Blog"
    languageName = "Français"

[Languages.pt]
    weight = 9
    title = "Kitty Cash Blog"
    languageName = "Português"

[Languages.it]
    weight = 10
    title = "Kitty Cash Blog"
    languageName = "Italiano"

[[menu.languages]]
  name = "English"
  weight = -1
  url = "/"
[[menu.languages]]
  name = "Español"
  weight = 4
  url = "/es/"
[[menu.languages]]
  name = "Deutsch"
  weight = 5
  url = "/de/"
[[menu.languages]]
  name = "Français"
  weight = 8
  url = "/fr/"
[[menu.languages]]
  name = "Português"
  weight = 9
  url = "/pt/"
[[menu.languages]]
  name = "Italiano"
  weight = 10
  url = "/it/"
